### ISSUE TITLE
Minecraft Server Forge v1.18.2 Error receiving packet 15 bug problem If i use this Teleport Ring...

### ISSUE THREAD

**Issue by Xiantrius** [kwpugh/gobber_forge#81]
Ring of Teleport [FORGE] i use last version RingOfTeleport-Forge-1.18.2-1.4.7.jar, please fix this thanks :).
```
[23:45:25] [Netty Epoll Server IO #3/ERROR] [minecraft/PacketEncoder]: Error receiving packet 15
java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "p_130078_" is null
        at net.minecraft.network.FriendlyByteBuf.m_130077_(FriendlyByteBuf.java:363) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.network.protocol.game.ClientboundChatPacket.m_5779_(ClientboundChatPacket.java:36) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:40) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.NettyPacketEncoderMixin,pl:mixin:APP:rei.mixins.json:MixinPacketEncoder,pl:mixin:A}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.NettyPacketEncoderMixin,pl:mixin:APP:rei.mixins.json:MixinPacketEncoder,pl:mixin:A}
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at net.minecraft.network.Connection.m_178303_(Connection.java:215) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.Connection.m_129520_(Connection.java:201) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.Connection.m_129514_(Connection.java:184) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9831_(ServerGamePacketListenerImpl.java:1521) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_141995_(ServerGamePacketListenerImpl.java:1506) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.lambda$sendMessage$12(ServerPlayer.java:1619) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at net.minecraft.network.Connection.m_178303_(Connection.java:217) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:204) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar%2350!/:4.1.68.Final] {}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
```

**Comment by kwpugh** [comment]
I'm no longer providing updates to 1.18.2

In the future, please post a copy of the full crash report.

**Comment by Xiantrius** [comment]
Yes, then I don't have to bother anymore if you're not willing to at least free your mod for 1.18.2 from bugs.
